# This is a basic workflow to help you get started with Actions

name: Chrome UI Tests

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs: 
      specs:
        description: 'Run All or unique spec'
        default: cypress/integration/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  chrome-ui-tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1,2]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Ping API (Heroku)
        uses: Leocardoso94/is-my-site-up@v1.2
        with:
          site: https://samuraibs-api-leo.herokuapp.com  

      - name: 'UI Tests - Chrome'
        uses: cypress-io/github-action@v2 # use the explicit version number
        with:
          # we have already installed all dependencies above
          install-command: yarn install
          wait-on: 'https://samuraibs-web-leo.herokuapp.com'
          wait-on-timeout: 120
          browser: chrome
          record: true
          parallel: true
          group: 'UI - Chrome'
          spec: ${{ github.event.inputs.specs }}
        env:
          TZ: America/Sao_Paulo
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
